/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ManaBotJava;

import Helpers.Downloader;
import org.junit.Test;

import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void checkDownloder_1v1() {
        System.out.println("Test: checkDownloader_1v1");

        Downloader dwnldr = new Downloader();
        assertNotNull(dwnldr);
        assertTrue(dwnldr.getUpdateStatus());
    }

    @Test
    public void checkDownloder_1v2() {
        System.out.println("Test: checkDownloader_1v2");

        Downloader dwnldr = new Downloader(true);
        assertNotNull(dwnldr);
        assertTrue(dwnldr.getUpdateStatus());
    }
}
