/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ManaBotJava;

import Helpers.Downloader;
import Helpers.JSONCardParser;
import static Helpers.JSONCardParser.parseJSONCards;


import org.json.simple.JSONObject;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    String dataFile = "./src/main/resources/AllPrintings.json";

    /*@Test
    public void checkDownloader_1() {
        System.out.println("Test: checkDownloader_1");

        Downloader dwnldr = new Downloader(false);
        System.out.println("Test functions done. Running asserts.");

        assertNotNull(dwnldr);
        assertTrue(dwnldr.getUpdateStatus());

        System.out.println("\n");
    }*/

    @Test
    public void checkJSONParse() {
        System.out.println("Test: checkJSONParse: get a JSONObject");

        JSONObject testObj = parseJSONCards(dataFile);
        System.out.println("Test functions done. Running asserts.");

        assertNotNull(testObj);
        //assertEquals("JSONObject",testObj.getClass().getSimpleName());

        System.out.println("\n");
    }

}
